DELETE FROM products_categories;
DELETE FROM products;
DELETE FROM categories;

TRUNCATE TABLE products RESTART IDENTITY CASCADE;
TRUNCATE TABLE categories RESTART IDENTITY CASCADE;
TRUNCATE TABLE products_categories RESTART IDENTITY CASCADE;

-- Insert 50 Categories
INSERT INTO categories (name) VALUES
('Electronics'),
('Furniture'),
('Clothing'),
('Toys'),
('Books'),
('Sports'),
('Home Appliances'),
('Automotive'),
('Health & Beauty'),
('Jewelry'),
('Food & Beverage'),
('Garden & Outdoors'),
('Music'),
('Computers'),
('Video Games'),
('Office Supplies'),
('Pet Supplies'),
('Baby Products'),
('Art & Craft'),
('Tools'),
('Gifts'),
('Party Supplies'),
('Travel'),
('Shoes'),
('Watches'),
('Bags'),
('Cleaning Supplies'),
('Luggage'),
('Photography'),
('Luxury'),
('Lingerie'),
('Cosmetics'),
('Gardening'),
('Camping'),
('Outdoor Gear'),
('Fitness Equipment'),
('Hobbies & Interests'),
('Home Decor'),
('Kitchenware'),
('Smart Home Devices'),
('Groceries'),
('Stationery'),
('Travel Accessories'),
('Fitness & Yoga'),
('Camping Gear'),
('Food Storage'),
('Personal Care'),
('Bedding & Linens'),
('Health Supplements'),
('Handbags'),
('Rugs & Carpets');

-- Insert 300 Products
INSERT INTO products (name, description, price) VALUES
('Smartphone', 'Latest model with advanced features and camera quality.', 599.99),
('Laptop', 'Powerful laptop with high processing speed and memory.', 899.99),
('Wireless Headphones', 'Noise-canceling headphones for premium sound experience.', 149.99),
('Refrigerator', 'Energy-efficient refrigerator with large storage capacity.', 499.99),
('Sofa', 'Comfortable sofa with a modern design.', 349.99),
('Washing Machine', 'High-efficiency washing machine with smart features.', 299.99),
('Electric Kettle', 'Fast boiling kettle with temperature control.', 29.99),
('Air Conditioner', 'Energy-saving air conditioner with remote control.', 249.99),
('Microwave Oven', 'Compact microwave oven for fast cooking.', 89.99),
('Dishwasher', 'Efficient dishwasher with adjustable racks.', 399.99),
('Smartwatch', 'Stylish smartwatch with fitness tracking and notifications.', 179.99),
('Camera', 'Professional camera with high resolution and excellent low-light performance.', 499.99),
('Coffee Maker', 'Automatic coffee maker with programmable features.', 69.99),
('Blender', 'High-speed blender for smoothies and soups.', 79.99),
('Toaster', '2-slice toaster with multiple heat settings.', 29.99),
('Hair Dryer', 'Powerful hair dryer with multiple speed settings.', 59.99),
('Electric Toothbrush', 'Rechargeable toothbrush with 2-minute timer.', 49.99),
('Dish Rack', 'Stainless steel dish rack for drying dishes.', 24.99),
('Cookware Set', 'Non-stick cookware set with 10 pieces.', 149.99),
('Mixer', 'Electric hand mixer with multiple speed settings.', 39.99),
('Couch', 'Stylish sectional couch for modern living rooms.', 499.99),
('Smart TV', '4K UHD smart TV with built-in streaming apps.', 399.99),
('Oven', 'Convection oven with adjustable temperature control.', 249.99),
('Power Bank', 'Portable power bank with 10,000 mAh capacity.', 29.99),
('Bluetooth Speaker', 'Compact and portable Bluetooth speaker with deep bass.', 49.99),
('Wireless Charger', 'Fast wireless charging pad for smartphones.', 19.99),
('Vacuum Cleaner', 'Lightweight vacuum cleaner with strong suction power.', 99.99),
('Electric Grill', 'Indoor electric grill with non-stick surface.', 79.99),
('Pressure Cooker', 'Multi-functional pressure cooker for fast cooking.', 89.99),
('Food Processor', 'Powerful food processor with various attachments.', 119.99),
('Stand Mixer', 'Heavy-duty stand mixer with multiple speed settings.', 249.99),
('Dehumidifier', 'Compact dehumidifier for small rooms.', 89.99),
('Heater', 'Portable space heater with adjustable settings.', 69.99),
('Fan', 'Oscillating tower fan with remote control.', 39.99),
('Electric Shaver', 'Rechargeable electric shaver for a smooth shave.', 69.99),
('Car Vacuum', 'Portable vacuum cleaner for car interiors.', 49.99),
('Smart Doorbell', 'Video doorbell with WiFi connectivity and motion detection.', 119.99),
('Electric Blanket', 'Soft electric blanket with heat settings.', 49.99),
('Camping Tent', 'Waterproof camping tent for 4 people.', 99.99),
('Sleeping Bag', 'Compact sleeping bag for outdoor adventures.', 29.99),
('Backpack', 'Durable backpack with multiple compartments.', 39.99),
('Sunglasses', 'UV-protection sunglasses with stylish frames.', 19.99),
('Winter Jacket', 'Waterproof winter jacket with fleece lining.', 79.99),
('Umbrella', 'Compact foldable umbrella for rainy days.', 14.99),
('Sneakers', 'Comfortable running sneakers with breathability.', 59.99),
('T-shirt', 'Casual cotton t-shirt available in various sizes.', 19.99),
('Jeans', 'Stretchable denim jeans with a comfortable fit.', 39.99),
('Leather Wallet', 'Genuine leather wallet with multiple compartments.', 29.99),
('Handbag', 'Stylish leather handbag with gold accents.', 69.99),
('Backpack', 'Fashionable leather backpack for everyday use.', 49.99),
('Jacket', 'Soft leather jacket with a modern look.', 119.99),
('Boots', 'Water-resistant boots perfect for winter weather.', 89.99),
('Sweater', 'Warm knitted sweater with a relaxed fit.', 49.99),
('Skirt', 'Stylish and comfortable skirt for casual wear.', 29.99),
('Belt', 'Genuine leather belt with a sleek buckle design.', 19.99),
('Watch', 'Classic wristwatch with a leather strap.', 129.99),
('Ring', 'Elegant silver ring with gemstone details.', 59.99),
('Necklace', 'Gold necklace with a delicate pendant.', 89.99),
('Earrings', 'Beautiful pearl earrings for special occasions.', 49.99),
('Bracelet', 'Fashionable bracelet with adjustable sizing.', 29.99),
('Sunglasses', 'UV-blocking sunglasses with polarized lenses.', 39.99),
('Yoga Mat', 'Non-slip yoga mat with extra cushioning.', 24.99),
('Exercise Ball', 'Durable exercise ball for fitness training.', 19.99),
('Resistance Bands', 'Set of resistance bands for home workouts.', 14.99),
('Dumbbells', 'Adjustable dumbbells for strength training.', 39.99),
('Jump Rope', 'Speed jump rope for cardio workouts.', 9.99),
('Treadmill', 'Motorized treadmill with adjustable incline.', 299.99),
('Exercise Bike', 'Stationary exercise bike with adjustable resistance.', 149.99),
('Kettlebell', 'Heavy-duty kettlebell for strength workouts.', 29.99),
('Boxing Gloves', 'Professional boxing gloves with padded support.', 49.99),
('Medicine Ball', 'Weighted medicine ball for functional training.', 39.99),
('Foam Roller', 'High-density foam roller for muscle recovery.', 19.99),
('Pilates Ring', 'Adjustable pilates ring for core workouts.', 14.99),
('Resistance Bands', 'Set of resistance bands for mobility and strength.', 22.99),
('Tennis Racket', 'High-performance tennis racket with durable strings.', 89.99),
('Golf Club', 'Lightweight golf club for precision shots.', 129.99),
('Fishing Rod', 'Durable fishing rod with ergonomic handle.', 39.99),
('Baseball Glove', 'Leather baseball glove for a secure grip.', 59.99),
('Soccer Ball', 'Professional quality soccer ball with optimal bounce.', 19.99),
('Baseball Bat', 'Wooden baseball bat with a sturdy handle.', 49.99),
('Running Shoes', 'Running shoes with breathable fabric and cushion.', 69.99),
('Yoga Blocks', 'Supportive yoga blocks for stability during poses.', 9.99),
('Hiking Boots', 'Durable hiking boots for outdoor adventures.', 99.99),
('Tent', '4-person tent with waterproof seams for camping.', 159.99),
('Sleeping Pad', 'Comfortable sleeping pad for outdoor camping.', 29.99),
('Camping Chair', 'Foldable camping chair with adjustable armrests.', 19.99),
('Cooler', 'Portable cooler for keeping drinks cold during outdoor activities.', 39.99),
('Flashlight', 'Heavy-duty flashlight with high brightness levels.', 19.99),
('Lantern', 'Rechargeable lantern with adjustable brightness.', 29.99),
('Water Bottle', 'Stainless steel water bottle for keeping drinks cold.', 14.99),
('Camping Stove', 'Compact stove for outdoor cooking.', 39.99),
('Travel Backpack', 'Durable backpack for travelers with compartments.', 49.99),
('Sleeping Bag', 'Cold-weather sleeping bag for camping trips.', 69.99),
('Travel Pillow', 'Memory foam travel pillow for comfort during flights.', 19.99),
('Travel Adapter', 'Universal travel adapter for international use.', 14.99),
('Luggage Set', '3-piece luggage set with sturdy wheels.', 149.99),
('Roller Skates', 'Adjustable roller skates for beginners and intermediates.', 39.99),
('Scooter', 'Electric scooter for fast and smooth commuting.', 199.99),
('Skateboard', 'High-quality skateboard with anti-slip deck.', 49.99),
('Bicycle', 'Mountain bike with suspension system for rough terrains.', 249.99),
('Riding Helmet', 'Protective riding helmet for safety during biking.', 39.99),
('Scooter Helmet', 'Lightweight helmet for safe scooter riding.', 29.99),
('Bicycle Pump', 'Portable bicycle pump for inflating tires on the go.', 14.99),
('Motorcycle Gloves', 'Heavy-duty gloves for motorcycle riding protection.', 29.99),
('Motorcycle Jacket', 'Leather motorcycle jacket with armor inserts.', 119.99),
('Motorcycle Helmet', 'Full-face helmet for maximum protection.', 89.99),
('Car Seat', 'Infant car seat with easy installation.', 129.99),
('Booster Seat', 'Adjustable booster seat for growing children.', 69.99),
('Stroller', 'Compact stroller with easy fold and adjustable handle.', 149.99),
('Crib', 'Convertible crib with adjustable mattress height.', 199.99),
('High Chair', 'Adjustable high chair for feeding babies and toddlers.', 99.99),
('Baby Monitor', 'Video baby monitor with night vision and audio.', 79.99),
('Diaper Bag', 'Stylish diaper bag with multiple compartments.', 39.99),
('Baby Carrier', 'Comfortable baby carrier with ergonomic design.', 59.99),
('Baby Blanket', 'Soft baby blanket made with hypoallergenic materials.', 24.99),
('Pacifier', 'BPA-free pacifier for soothing babies.', 4.99),
('Diapers', 'Soft and absorbent diapers for all sizes.', 29.99),
('Baby Wipes', 'Gentle baby wipes for sensitive skin.', 9.99),
('Baby Lotion', 'Hypoallergenic baby lotion for smooth skin.', 7.99),
('Toys', 'Educational toy set for early learning.', 19.99),
('Playmat', 'Soft playmat for safe baby crawling.', 24.99);

INSERT INTO products_categories (product_id, category_id) 
SELECT p.id, c.id
FROM products p, categories c
WHERE p.id <= 300 
  AND c.id <= 30
  AND random() < 0.25; 